name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: |
          git config --global user.email "sajal.shres@gmail.com"
          git config --global user.name "sajalshres"
      - run: npm ci
      - run: npm run deploy
